### ISSUE TITLE
Can we use other libraries besides pigpio?

### ISSUE THREAD

**Issue by celenamichaud** [Herring-UGAECSE-2920-S22/Class-Instructions#11]
Our team is interested in using the Rpi.GPIO library instead of pigpio. Is the pigpio library selected because of its specific capabilities that we might need , or can we use the rpi.GPIO library?

**Comment by zvs26462** [comment]
I answered this via email but I'm answering here for the entire class to reference. You can use whatever library works best for your design. Pigpio is just a recommendation or a reference point for people who may not know of other libraries.
