### ISSUE TITLE
Deliverable 4 Instructions

### ISSUE THREAD

**Issue by sglove2001** [Herring-UGAECSE-2920-S22/Class-Instructions#12]
For deliverable 4 can we have some clarification on the terms used in the GPIO diagram requirements. 
Such as:
"Functional Name For Project"
-very vague requirement, does Project mean pin of the gpio
"State Used for Project"
- does this mean state of the pin?
"Pull up or Pull down (if any)"
- pull up or pull down what? my group and I are not familiar with what this defines.
"switch needed to set GPIO"
- very vague in terms of defining what switch

**Comment by Joseph4Zimmer** [comment]
For the "Functional Name For Project", I sent an email to the TA and she responded with: 
"The word project might be a bit confusing it’s just the functional name for that connection (relating to the what the GPIO is being used for)"

**Comment by zvs26462** [comment]
Let me know if that^ response resolves the issue, or if you have any more questions. If not I'll close this issue
