### ISSUE TITLE
Need a webhook added to our repo

### ISSUE THREAD

**Issue by Kasra-G** [Herring-UGAECSE-2920-S22/Class-Instructions#13]
We would like to add a webhook to our (team17) github repo to view events externally but we do not have admin powers. If you dont mind, we need the following webhook to be added to our repo:  

https://www.yappybots.tk/github

Webhooks can be found at settings > webhooks > add webhook.
We also request that the "send me everything" box is checked so we get all updates. This should only take a few minutes to do. Thank you very much!

**Comment by Kasra-G** [comment]
to be clear i only specified Zaniyah because that is the person listed as a contributor not on our team

**Comment by zvs26462** [comment]
We've added the webhook, let me know if everything is set up.
