### ISSUE TITLE
Back Wheel and Extension Cord Affecting Driving Car

### ISSUE THREAD

**Issue by Kpmorin895** [Herring-UGAECSE-2920-S22/Class-Instructions#15]
For our car, the direction that it moves in a straight line in particular is heavily dependent on the back wheel placement and it seems that it is very difficult to not affecting the direction of the car when following it around with an extension cord. Is there some way around these issues that we need to figure out or is it something that we won't be able to change but try to account for as much as possible?

**Comment by zvs26462** [comment]
As far as the back wheel placement, this is something your team will want to account for. We do understand that navigating with the extension cord may cause some difficulty, one tip is to make sure someone on your team is designated to hold the block of the 12V power supply as well as the extension cord.
