### ISSUE TITLE
Issue with Class-Instructions/Deliverables/setup/pi_setup.md

### ISSUE THREAD

**Issue by wtk75435** [Herring-UGAECSE-2920-S22/Class-Instructions#2]
The links on the pi setup guide aren't working; they just give a 404 error. Anyone else having this problem?

**Comment by AnthonyPetti** [comment]
I tested out several links in the file and I didn't have any issues. Might've just been internet issues at the time of accessing.

**Comment by TJFerg** [comment]
Has this been resolved?

**Comment by wtk75435** [comment]
I had to go through github and open the deliverable 2 instructions rather than open them from the class schedule. That was the solution, but the class schedule still doesn't show the complete instructions.

Thanks,

Will Kellum
________________________________

**Comment by TJFerg** [comment]
Gotcha. We are working on updating the schedule to the proper links. 
Also we made it wear you had to dive in a little deeper to stuff to set it up. We did this to start getting you all into the idea of knowing where to look for code and such as you will have to later on in the project.
