### ISSUE TITLE
Missing car parts

### ISSUE THREAD

**Issue by CamdenWebb** [Herring-UGAECSE-2920-S22/Class-Instructions#3]
My group did not receive any of the PCB standoff parts. We made a checklist and seemed to have everything else we need. How should my group and I go about getting these parts? Would waiting until class next Wednesday to retrieve the part work best?

**Comment by AnthonyPetti** [comment]
I believe those parts haven't come in for any group yet... could be wrong though.

**Comment by TJFerg** [comment]
There is a hold on the standoffs. As long as everything else is there you should be fine.
