### ISSUE TITLE
1st Deliverable Github Exercise Issue

### ISSUE THREAD

**Issue by Kpmorin895** [Herring-UGAECSE-2920-S22/Class-Instructions#5]
In the Github exercise in the first deliverable, it says to create a Python script under a directory named HelloWorldScripts, does that require the use of the os module in Python, or is there another way to create a directory in Python?

**Comment by TJFerg** [comment]
You are suppose to create a new repository called _HelloWorldScripts_. Then add you code there. 
The repository is not needed but understanding how to create them will be useful in the end.

**Comment by TJFerg** [comment]
If you need further explanation please reach out
