### ISSUE TITLE
Jack Adapter

### ISSUE THREAD

**Issue by Kpmorin895** [Herring-UGAECSE-2920-S22/Class-Instructions#7]
Is this the Jack Adapter?
![thumbnail_image0 (1)](https://user-images.githubusercontent.com/97573359/149840570-357f9397-009c-48f2-ae8b-1b3320982aad.jpg)

**Comment by TJFerg** [comment]
Yes it is. It will be used to take the power from the 12v and give you a positive and negative lead.
