### ISSUE TITLE
Kernal panic

### ISSUE THREAD

**Issue by byh33328** [Herring-UGAECSE-2920-S22/Class-Instructions#8]
Our micro SD card doesn't seem to want to boot up correctly into the raspberry pi and we are getting a kernal panic.  The last line says:

---[ end Kernal panic - not syncing: VFS: Unable to mount root fs on unknown-block(179,2) ]---

We currently do not know what to do and cannot proceed as we are stuck.

**Comment by TJFerg** [comment]
Okay, I would have to see this in person to help. I can be at drify tomorrow around 12:30-1:30 and then before class to meet and figure it out. Let me know if this works for your team.

**Comment by byh33328** [comment]
I'm not going to be available, but will let my group know about it to see if any of them can make it.  They will post here if they can.  ![IMG_20220118_185713585.jpg](https://user-images.githubusercontent.com/97480498/150061613-aaa3e485-0733-488d-af79-e7cfe95cb335.jpg)

**Comment by byh33328** [comment]
A team member of mine will meet you today, just let us know which room.

**Comment by TJFerg** [comment]
I will be for a little bit of time from 12:30-1:30 and I can meet you around room 1355

**Comment by hayden-o** [comment]
I will be there at 12.
